---
- name: Create temporary directory
  file:
    path: "{{ var_path }}/pulp"
    state: directory

- name: Copy build files
  copy:
    src: '{{ project_root }}/docker/pulp/{{ item.path }}'
    dest: '{{ var_path }}/pulp/{{ item.path }}'
    mode: '{{ item.mode }}'
    remote_src: true
  with_items:
    - {'path': 'Dockerfile', 'mode': '0644'}
    - {'path': 'entrypoint.sh', 'mode': '0755'}
    - {'path': 'run.sh', 'mode': '0755'}
    - {'path': 'tmux.conf', 'mode': '0755'}

- name: Generate random secret for Django
  shell: cat /dev/urandom | tr -dc 'a-z0-9!@#$%^&*(\-_=+)' | head -c 50
  register: django_secret

- name: Copy pulp settings
  copy:
    src: '{{ source_root }}/pulp/pulpcore/pulpcore/etc/pulp/settings.py'
    dest: '{{ var_path }}/pulp/settings.py'
    remote_src: true

- name: Modify pulp settings
  blockinfile:
    path: '{{ var_path }}/pulp/settings.py'
    block: |
      DEBUG = True
      SECRET_KEY = '{{ django_secret.stdout }}'
      DATABASES = {
          'default': {
              'ENGINE': 'django.db.backends.postgresql_psycopg2',
              'HOST': 'postgres',
              'USER': 'pulp',
              'PASSWORD': 'pulp',
              'NAME': 'pulp',
              'CONN_MAX_AGE': 0,
          }
      }
      REDIS_URL = 'redis://redis/'

- name: Build pulp requirements
  shell: |
    pip-compile setup.py > "{{ var_path }}/pulp/pulp-requirements.txt"
  args:
    chdir: "{{ source_root }}/pulp/pulpcore"

- name: Build pulp plugin requirements
  shell: |
    pip-compile setup.py | sed '/^pulpcore/d' > "{{ var_path }}/pulp/pulp-plugin-requirements.txt"
  args:
    chdir: "{{ source_root }}/pulp/plugin"

- name: Build pulp galaxy requirements
  shell: |
    pip-compile setup.py | sed '/^pulpcore/d' > "{{ var_path }}/pulp/pulp-galaxy-requirements.txt"
  args:
    chdir: "{{ source_root }}/pulp_galaxy"

- name: Build pulp image
  docker_image:
    name: 'galaxy-dev/pulp'
    path: '{{ var_path }}/pulp'
    dockerfile: '{{ var_path }}/pulp/Dockerfile'
    force: true
